name = "DSAGAnalysis"
uuid = "5052dac0-a9cd-462e-8b7e-260df0b3fb31"
authors = ["Albin Severinson <albin@severinson.org> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
